import assert from 'node:assert/strict';
import {createJiti} from 'jiti';
const jiti=createJiti(import.meta.url);
const {AgentSession}=await jiti.import('../node_modules/@earendil-works/pi-coding-agent/dist/core/agent-session.js');
const {makeDeliverySink}=await jiti.import('../src/push.ts');
const rows=[],errors=[]; let reject=true,calls=0,actions;
const host={sendCustomMessage:async(m)=>{calls++;await new Promise(r=>setTimeout(r,5));if(reject)throw Error('durable rejected');rows.push({type:'custom_message',...m});}};
AgentSession.prototype._bindExtensionCore.call(host,{bindCore:a=>{actions=a;},emitError:e=>errors.push(e)});
const sink=makeDeliverySink({...actions,on(){}},{getBranch:()=>rows});
const msg={content:'final',details:{name:'leaf',kind:'done',eventId:'event-1'},wake:true};
await assert.rejects(async()=>{await sink(msg);},/pending|confirm|ack/i,'void dispatch is not durable confirmation');
await new Promise(r=>setTimeout(r,15));
assert.equal(rows.length,0);assert.equal(errors.length,1);
await assert.rejects(async()=>{await sink(msg);},/pending|confirm|ack/i);
assert.equal(calls,1,'pending token never duplicates enqueue');
reject=false;
const success={...msg,details:{...msg.details,eventId:'event-2'}};
await assert.rejects(async()=>{await sink(success);},/pending/);
await new Promise(r=>setTimeout(r,15));
await sink(success);
assert.equal(rows.length,1,'ack only after actual SDK asynchronous custom entry persists');
assert.equal(calls,2);
const quiet={...success,details:{...success.details,eventId:'event-3'},wake:false,deliverAs:'nextTurn'};
let queued;host.sendCustomMessage=async m=>{calls++;queued=m;};
await assert.rejects(async()=>{await sink(quiet);},/pending/);
await new Promise(r=>setTimeout(r,5));
await assert.rejects(async()=>{await sink(quiet);},/pending/);
rows.push({type:'custom_message',...queued});await sink(quiet);
assert.equal(calls,3,'nextTurn queue is not redelivered while waiting for branch entry');
const {mkdtempSync,writeFileSync,rmSync}=await import('node:fs');
const {tmpdir}=await import('node:os');const {join}=await import('node:path');
const sp=await jiti.import('../src/spawn.ts');const dl=await jiti.import('../src/delivery.ts');
const dir=mkdtempSync(join(tmpdir(),'sdk-adoption-'));
try {
 const root=join(dir,'root'),mid=join(dir,'mid'),leaf=join(dir,'leaf');
 for(const p of [root,mid,leaf])writeFileSync(p,'');
 const owner={name:'mid',kind:'pi',paneId:'w1:mid',sessionPath:mid,stance:'autonomous'};
 const child={name:'leaf',kind:'pi',paneId:'w1:leaf',sessionPath:leaf,stance:'autonomous',lineage:{ownerSession:mid,rootSession:root}};
 sp.writePersistedRegistry(mid,[child]);writeFileSync(leaf+'.exit',JSON.stringify({type:'done',text:'final',rootSession:root}));
 let closed=0;reject=true;host.sendCustomMessage=async()=>{await Promise.resolve();throw Error('durable rejected');};
 const adoptedSink=makeDeliverySink({...actions,on(){}},{getBranch:()=>rows});
 const deps={registry:()=>new Map([['mid',owner]]),sessionPath:root,load:()=>({notifications:'normal'}),fleet:{ok:true,data:[{paneId:'w1:leaf',agentStatus:'done'}]},push:adoptedSink,closePane:async()=>{closed++;}};
 await dl.deliverOnce(deps);await new Promise(r=>setTimeout(r,10));await dl.deliverOnce(deps);
 assert.equal(closed,0,'real SDK void async failure never recycles orphan pane');
 const saved=sp.readPersistedRegistry(mid)[0];assert.equal(saved.delivery,undefined);assert.match(saved.pushError,/confirmation/);
}finally{rmSync(dir,{recursive:true,force:true});}
console.log('delivery-sdk: passed');
