import assert from 'node:assert/strict';
import { createJiti } from 'jiti';
import { resolve } from 'node:path';
const jiti = createJiti(import.meta.url);
const { createReceiverInbox, registerReceiverInbox } = await jiti.import(resolve('src/inbox.ts'));
let now = 0;
const delivered = [], receipts = [];
const inbox = createReceiverInbox({ now: () => now, deliver: async m => delivered.push(m.text), receipt: async r => receipts.push(r) });
const message = (from, text) => ({ from, to: 'receiver', body: text, text });
const stored = [];
const queueOnly = createReceiverInbox({ persist: async m => stored.push(m.text), deliver: () => { throw Error('QueueOnly must not deliver into a turn'); }, receipt: async r => receipts.push(r) });
await queueOnly.receive(message('sender', 'offline-safe'));
assert.deepEqual(stored, ['offline-safe'], 'QueueOnly durably accepts without invoking conversational delivery');
inbox.setBusy(true);
await inbox.receive(message('a', '0'));
assert.deepEqual(delivered, [], 'busy input is held by receiver, without sender opting in');
await inbox.settle();
assert.deepEqual(delivered, ['0'], 'settled receiver drains without another inbound call');
inbox.setBusy(true);
for (let i=1; i<=10; i++) await inbox.receive(message(i === 1 ? 'dropped-a' : i === 2 ? 'dropped-b' : 'b', String(i)));
assert.equal(receipts.length, 2, 'one receiver aggregate plus immediate notification to each actual dropped sender');
assert.deepEqual(receipts.map(r=>r.notify), [['dropped-a'], ['dropped-b']]);
assert.equal(receipts[1].receiver, false, 'later loss folds into receiver aggregate');
await inbox.settle();
assert.deepEqual(delivered, ['0','3','4','5','6','7','8','9','10'], 'only pending oldest is dropped; previously delivered untouched');
const limited = [], rate = [];
const limiter = createReceiverInbox({ now:()=>now, deliver:m=>limited.push(m.text), receipt:r=>rate.push(r) });
for (let i=0;i<22;i++) await limiter.receive(message('fast', String(i)));
assert.equal(limited.length,20); assert.equal(rate.length,1);
assert.deepEqual(rate[0].notify,['fast']); assert.match(rate[0].text,/same OS user/);
await limiter.receive(message('other','other')); assert.equal(limited.at(-1),'other');
now=10000; await limiter.receive(message('fast','cooled')); assert.equal(limited.at(-1),'cooled');
let failing = true; const recovered = [], failures = [];
const retry = createReceiverInbox({ deliver:m=>{ if(failing) throw Error('sink refused'); recovered.push(m.text); }, receipt:r=>failures.push(r) });
await assert.rejects(retry.receive(message('sender','retained')),/sink refused/);
assert.equal(failures[0].kind,'delivery-failed');
failing=false; await retry.settle(); assert.deepEqual(recovered,['retained']);
const handlers = new Map(), custom = [], user = [];
const pi = {on:(n,h)=>handlers.set(n,h),sendMessage:(m,o)=>custom.push({m,o}),sendUserMessage:t=>user.push(t)};
const ctx={ui:{notify:()=>{}}};
registerReceiverInbox(pi,{parse:t=>t.startsWith('envelope:')?{from:'a',to:'r',body:t}:undefined,deliver:()=>({action:'continue'})});
const input=async text=>handlers.get('input')({type:'input',text,source:'interactive'},ctx);
assert.equal((await input('raw blocked answer')).action,'continue','raw answer exempt');
await handlers.get('agent_start')({},ctx);
assert.equal((await input('envelope:held')).action,'handled'); assert.equal(user.length,0);
await handlers.get('agent_settled')({},ctx); assert.equal(user.length,1);
const internal=await handlers.get('input')({type:'input',text:user[0],source:'extension'},ctx);
assert.equal(internal.action,'transform');assert.equal(internal.text,'envelope:held');
assert.equal((await input('<agent-receipt>\nnotice\n</agent-receipt>')).action,'handled');
assert.equal(custom[0].m.customType,'herdr-inbox-receipt'); assert.equal(custom[0].o.triggerTurn,false);
assert.equal(user.length,1,'receipts never enter conversational queue or generate receipts');
console.log('GREEN receiver admission, shared pending cap, auto-drain, actual sender receipts, clock, failure retry and no loops');
