import assert from 'node:assert/strict';
import { getEventListeners } from 'node:events';
import { createJiti } from 'jiti';
import { resolve } from 'node:path';
const jiti = createJiti(import.meta.url);
const { createInputWake, defaultInputWake, registerResultInputWake, waitForInputOrPoll } = await jiti.import(resolve('src/inputwake.ts'));
const { getAgentResult } = await jiti.import(resolve('src/tools/result.ts'));
const fakePi = () => {
 const events = new Map();
 return { on(name, handler) { events.set(name, handler); }, fire(name) { events.get(name)?.({}); } };
};
const scope = createInputWake();
let listeners = 0;
const tracked = { get epoch() { return scope.epoch; }, subscribe(fn) { listeners++; const off = scope.subscribe(fn); return () => { listeners--; off(); }; } };
await waitForInputOrPoll(tracked, 0, 1);
assert.equal(listeners, 0, 'poll winner removes wake subscriber');
const epoch = scope.epoch;
const waiting = waitForInputOrPoll(tracked, epoch, 60000);
scope.advance();
await waiting;
assert.equal(listeners, 0, 'input winner removes subscriber and timer');
await waitForInputOrPoll(tracked, epoch, 60000);
assert.equal(listeners, 0, 'arrival before subscribe returns immediately and cleans up');
const closingRace = { epoch: 0, subscribe(fn) { this.epoch++; fn(); return () => { listeners--; }; } };
listeners++;
const subscribeAbort = new AbortController();
await waitForInputOrPoll(closingRace, 0, 60000, subscribeAbort.signal);
assert.equal(listeners, 0, 'synchronous subscribe arrival cleans its newly returned disposer');
assert.equal(getEventListeners(subscribeAbort.signal, 'abort').length, 0, 'synchronous subscribe arrival leaves no abort listener');
const abort = new AbortController();
const cancelled = waitForInputOrPoll(tracked, scope.epoch, 60000, abort.signal);
abort.abort(); await cancelled;
assert.equal(listeners, 0, 'abort removes subscriber and timer');
const sharedEpoch = scope.epoch;
const parallel = [waitForInputOrPoll(tracked, sharedEpoch, 60000), waitForInputOrPoll(tracked, sharedEpoch, 60000)];
scope.advance(); await Promise.all(parallel);
assert.equal(listeners, 0, 'input broadcasts to all foreground waiters');
const record = { name: 'child', kind: 'pi', stance: 'autonomous', paneId: 'owned', sessionPath: 'unused', submitted: true, sawWorking: true, spawnedAt: Date.now() };
const base = { registry: () => new Map([['child', record]]), readSidecar: () => ({ state: 'missing' }), extract: () => null, readActivity: () => ({ state: 'missing' }), pollMs: 60000 };
let reads = 0;
const duringInspect = await getAgentResult({ target: 'child', wait: true }, { ...base, inputWake: scope, status: async () => { reads++; scope.advance(); return { ok: true, data: 'working' }; } });
assert.equal(duringInspect.data.interruptedByInput, true, 'arrival during async inspection releases wait');
assert.equal(duringInspect.data.interim, true);
assert.equal(reads, 1);
const expiry = await getAgentResult({ target: 'child', wait: 5 }, { ...base, inputWake: scope, status: async () => ({ ok: true, data: 'working' }) });
assert.equal(expiry.data.interim, true, 'bounded wait still returns the real interim view on expiry');
assert.equal(expiry.data.interruptedByInput, undefined);
const inspectAbort = new AbortController();
const promise = getAgentResult({ target: 'child', wait: true }, { ...base, inputWake: scope, signal: inspectAbort.signal, status: async () => ({ ok: true, data: 'working' }) });
await new Promise(r => setTimeout(r, 1)); inspectAbort.abort();
assert.equal((await promise).error.message, 'aborted');
const one = fakePi(); registerResultInputWake(one);
const original = defaultInputWake(); one.fire('input'); assert.equal(original.epoch, 0, 'ordinary input does not interrupt a wait');
const legacy = await getAgentResult({ target: 'child', wait: 1 }, { ...base, status: async () => { one.fire('input'); return { ok: true, data: 'working' }; } });
assert.equal(legacy.data.interruptedByInput, undefined, 'ordinary input leaves legacy wait intact');
let state = 'working';
const background = getAgentResult({ target: 'child', wait: true }, { ...base, inputWake: null, pollMs: 1, status: async () => ({ ok: true, data: state }) });
one.fire('input');
let prematurelyDone = false; background.then(() => { prematurelyDone = true; });
await new Promise(r => setTimeout(r, 5));
assert.equal(prematurelyDone, false, 'background wait does not return on foreground input');
state = 'done'; assert.equal((await background).data.status, 'done');
one.fire('session_start'); assert.notEqual(defaultInputWake(), original);
const fresh = defaultInputWake(); assert.equal(fresh.epoch, 0, 'session replacement creates a fresh epoch');
const two = fakePi(); registerResultInputWake(two);
assert.throws(() => defaultInputWake(), /Multiple pi-herdr sessions/, 'ambiguous default cannot wake another SDK session');
const explicit = await getAgentResult({ target: 'child', wait: 1 }, { ...base, inputWake: fresh, status: async () => { one.fire('input'); return { ok: true, data: 'working' }; } });
assert.equal(explicit.data.interruptedByInput, undefined, 'explicit scope ignores ordinary input');
two.fire('session_shutdown'); assert.equal(defaultInputWake(), fresh);
one.fire('session_shutdown'); assert.equal(defaultInputWake(), undefined);
console.log('GREEN input wake races, abort, cleanup, foreground/background, lifecycle and multi-session isolation');
