import assert from 'node:assert/strict';
import { createJiti } from 'jiti';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const jiti = createJiti(import.meta.url);
const { waitForAgentEvent, createEventAvailability } = await jiti.import('../src/tools/wait.ts');
const { deliverOnce } = await jiti.import('../src/delivery.ts');
const { registerResultTool } = await jiti.import('../src/tools/result.ts');
const { registerParentDelivery } = await jiti.import('../src/parent-delivery.ts');
const dir = mkdtempSync(join(tmpdir(), 'spec43-t10-'));
try {
 const host = join(dir,'host.jsonl'); writeFileSync(host,'');
 const child = join(dir,'child.jsonl'); writeFileSync(child,'');
 let record = { name:'worker', kind:'pi', stance:'autonomous', paneId:'w1:p1', sessionPath:child, agentId:'agent', runId:'run', sequence:1 };
 const registry = () => new Map([['worker',record]]);
 let live = 'blocked';
 const status = async () => ({ok:true,data:live});
 const availability = createEventAvailability({ registry, status, pollMs:2 });
 const blocked = await waitForAgentEvent({target:'worker',timeout:20},{availability});
 assert.equal(blocked.data.status,'available','blocked is waitable without a terminal declaration');
 assert.equal(blocked.data.kind,'blocked'); assert.equal(blocked.data.eventId,undefined);
 let tool; registerResultTool({ on(){},registerTool(t){tool=t;} },{registry,status});
 const call = params => tool.execute('call',{target:'worker',...params},undefined,undefined,{sessionManager:{getSessionFile:()=>host}});
 assert.equal((await call({})).details.status,'blocked');
 assert.equal((await call({ack:{eventId:'run',agentId:'agent',runId:'run',sequence:1,hostFile:host}})).isError,true);
 const pushes=[];
 const deps = {registry,push:m=>pushes.push(m),fleet:{ok:true,data:[{paneId:'w1:p1',agentStatus:'blocked'}]},load:()=>({notifications:'quiet'}),sessionPath:host};
 await deliverOnce(deps);
 assert.equal(pushes[0].wake,false,'blocked cannot override quiet');
 assert.equal(pushes[0].details.agentId,'agent'); assert.equal(record.delivery,undefined);
 const firstId=pushes[0].details.noticeId;
 record=JSON.parse(JSON.stringify(record)); await deliverOnce(deps);
 assert.equal(pushes.length,1,'reload does not duplicate the same blocked episode');
 deps.fleet.data[0].agentStatus='working'; await deliverOnce(deps);
 assert.equal(pushes.at(-1).details.kind,'blocked-recovered'); assert.equal(pushes.at(-1).wake,false);
 live='working'; assert.equal((await waitForAgentEvent({target:'worker',timeout:2},{availability})).data.status,'timeout');
 deps.fleet.data[0].agentStatus='blocked'; await deliverOnce(deps);
 assert.notEqual(pushes.at(-1).details.noticeId,firstId,'new blocked episode has a distinct receiver notice');
 const event={type:'error',text:'[completion error: retries exhausted]',errorMessage:'retries exhausted',eventId:'failure-event',agentId:'agent',runId:'run',sequence:1};
 writeFileSync(child+'.exit',JSON.stringify(event));
 const waiting=await waitForAgentEvent({target:'worker',timeout:5},{availability});assert.equal(waiting.data.eventId,'failure-event');
 const failure=await call({});assert.equal(failure.details.status,'error');assert.equal(failure.details.result,event.text);assert.equal(failure.details.delivery.eventId,event.eventId);
 assert.equal((await call({})).details.result,undefined,'terminal failure body uses the same exclusive ledger claim as success');
 writeFileSync(child+'.exit',JSON.stringify({...event,runId:'stale-run'}));
 assert.equal((await waitForAgentEvent({target:'worker',timeout:2},{availability})).data.status,'timeout','old run failure cannot satisfy a current-run wait');
 const handlers=new Map(), dispatches=[];
 const parent=registerParentDelivery({on(n,h){handlers.set(n,h);}}, m=>dispatches.push(m),()=> 'normal');
 for(const kind of ['blocked','blocked-recovered','error','stall-recovered']) parent.accept({content:kind,details:{name:'worker',kind},wake:true});
 assert.equal(dispatches.length,0,'late notices do not wake a finished parent');
 handlers.get('before_agent_start')(); assert.equal(dispatches.length,4); assert.ok(dispatches.every(m=>!m.wake&&m.deliverAs==='nextTurn'));
 console.log('spec43 T10: blocked wait/ACK refusal, quiet policy, stable episodes, recovery and finished parent passed');
} finally { rmSync(dir,{recursive:true,force:true}); }
