import assert from 'node:assert/strict';
import {createJiti} from 'jiti';
import {mkdtempSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chmodSync} from 'node:fs';
import {spawn} from 'node:child_process';
const jiti=createJiti(import.meta.url);
const packageFiles=JSON.parse(readFileSync(new URL('../package.json',import.meta.url),'utf8')).files;
assert.ok(packageFiles.includes('src/**/*.mjs'),'published package includes native worker and shared transport');
assert.ok(packageFiles.includes('src/**/*.d.mts'),'published package includes strict TypeScript declarations for the shared transport');
const {registerChildExtension}=await jiti.import('../src/child.ts');
const {deliverOnce}=await jiti.import('../src/delivery.ts');
const {getAgentResult}=await jiti.import('../src/tools/result.ts');
const dir=mkdtempSync(join(tmpdir(),'spec43-t2-'));
const { ensureHerdrVersion, resolveHerdrBin, runHerdrCommand } = await import('../src/herdr-transport.mjs');
const fakeHerdr=join(dir,'herdr-fixture.mjs');
writeFileSync(fakeHerdr,`#!${process.execPath}\nif(process.argv[2]==='--version'){process.stdout.write('herdr '+(process.env.PI_HERDR_TEST_OLD?'0.8.9':'0.9.2')+'\\n');process.exit(0)} const error=process.argv[2]==='failure'; console.log(JSON.stringify(error?{ok:false,error:{code:'pane_not_found',message:'fixture missing'}}:{ok:true,result:{agents:[]}})); process.exit(error?1:0);`);
chmodSync(fakeHerdr,0o700);
const keys=['PI_HERDR_SESSION','PI_HERDR_AGENT_ID','PI_HERDR_RUN_ID','PI_HERDR_SEQUENCE','PI_HERDR_AUTO_EXIT','PI_HERDR_ACTIVITY_FILE','HERDR_PANE_ID'];
const old=keys.map(k=>process.env[k]);
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function runWorkerCase(mode,{ownerMismatch=false,runMismatch=false}={}) {
 const session=join(dir,`worker-${mode}-${Date.now()}.jsonl`);
 const intentPath=`${session}.recycle.json`;
 const trace=join(dir,`worker-${mode}.jsonl`);
 const bin=join(dir,`herdr-${mode}.mjs`);
 writeFileSync(session+'.exit',JSON.stringify({eventId:'event',runId:runMismatch?'different-run':'run',agentId:'agent'}));
 const ownerSession=ownerMismatch?join(dir,'owner-session.jsonl'):undefined;
 if(ownerSession) writeFileSync(ownerSession+'.registry.json',JSON.stringify([{agentId:'agent',runId:'different-run',paneId:'w1:p1'}]));
 writeFileSync(intentPath,JSON.stringify({pending:true,eventId:'event',runId:'run',agentId:'agent',sequence:1,sessionPath:session,paneId:'w1:p1',name:'worker',...(ownerSession?{ownerSession}:{})}));
 writeFileSync(bin,`#!${process.execPath}\nimport {appendFileSync} from 'node:fs'; const mode=${JSON.stringify(mode)}; const args=process.argv.slice(2); appendFileSync(${JSON.stringify(trace)},JSON.stringify(args)+'\\n'); if(args[0]==='--version'){if(mode==='version-failure'){console.error(JSON.stringify({ok:false,error:{code:'herdr_unavailable',message:'version fixture failed'}}));process.exit(1)} console.log('herdr 0.9.3');process.exit(0)} if(args[0]==='agent'){console.log(JSON.stringify(mode==='malformed-list'?{ok:true,result:{agents:null}}:{ok:true,result:{agents:[]}}));process.exit(0)} if(args[0]==='pane'&&args[1]==='list'){console.log(JSON.stringify({ok:true,result:mode==='missing-pane-list'?{}:{panes:mode==='malformed-pane-list'?null:mode==='empty-pane-list'?[]:[{pane_id:'w1:p1'}]}}));process.exit(0)} if(args[0]==='pane'&&args[1]==='close'){if(mode==='close-failure'){console.error(JSON.stringify({ok:false,error:{code:'pane_close_failed',message:'close fixture failed'}}));process.exit(1)} console.log(JSON.stringify({ok:true,result:{}}));process.exit(0)} process.exit(2);`);
 chmodSync(bin,0o700);
 const child=spawn(process.execPath,[join(new URL('../src/recycle-worker.mjs',import.meta.url).pathname),intentPath,bin],{stdio:'ignore'});
 const exited=new Promise(resolve=>child.once('close',resolve));
 const readIntent=()=>JSON.parse(readFileSync(intentPath,'utf8'));
 const wanted=mode==='pane-exists'?'pane-exists':mode==='empty-pane-list'?'empty-pane-list':ownerMismatch?'owner-mismatch':runMismatch?'run-mismatch':'error';
 const end=Date.now()+8000;
 while(Date.now()<end){
  const state=readIntent();
  if((wanted==='error'&&state.pending&&state.error)||(wanted==='owner-mismatch'&&!state.pending&&state.error==='registry ownership changed')||(wanted==='run-mismatch'&&!state.pending&&state.error==='stale close intent refused')||(wanted==='pane-exists'&&!state.pending&&!state.error)||(wanted==='empty-pane-list'&&!state.pending&&!state.error)) break;
  if(child.exitCode!==null) throw new Error(`worker exited before expected receipt for ${mode}: ${JSON.stringify(state)}`);
  await delay(20);
 }
 const state=readIntent();
 child.kill('SIGTERM'); await exited;
 return {state,commands:existsSync(trace)?readFileSync(trace,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[]};
}
try {
 const previousHerdrBinPath=process.env.HERDR_BIN_PATH;
 process.env.HERDR_BIN_PATH=fakeHerdr;
 assert.equal(resolveHerdrBin(),fakeHerdr,'worker-specific binary override wins consistently in both entry points');
 previousHerdrBinPath===undefined?delete process.env.HERDR_BIN_PATH:process.env.HERDR_BIN_PATH=previousHerdrBinPath;
 assert.deepEqual(await ensureHerdrVersion(fakeHerdr), { ok: true, data: { major: 0, minor: 9, patch: 2 } });
 process.env.PI_HERDR_TEST_OLD='1';
 const tooOld=await ensureHerdrVersion(fakeHerdr);
 delete process.env.PI_HERDR_TEST_OLD;
 assert.equal(tooOld.ok,false);
 assert.equal(tooOld.error.code,'HERDR_TOO_OLD');
 const transportSuccess=await runHerdrCommand(fakeHerdr,['success']);
 assert.deepEqual(transportSuccess,{ok:true,data:{agents:[]}});
 const transportFailure=await runHerdrCommand(fakeHerdr,['failure']);
 assert.equal(transportFailure.ok,false);
 assert.equal(transportFailure.error.code,'NOT_FOUND');
 assert.equal(transportFailure.error.message,'fixture missing');
 const versionFailure=await runWorkerCase('version-failure');
 assert.equal(versionFailure.state.pending,true,'version probe failure stays retryable');
 assert.match(versionFailure.state.error,/VALIDATION_ERROR|HERDR_UNAVAILABLE/);
 const malformedList=await runWorkerCase('malformed-list');
 assert.equal(malformedList.state.pending,true,'non-array agent list is not an empty fleet');
 assert.match(malformedList.state.error,/agents.*array/i);
 for(const mode of ['missing-pane-list','malformed-pane-list']) {
  const invalidPanes=await runWorkerCase(mode);
  assert.equal(invalidPanes.state.pending,true,'missing/invalid pane list is not proof the pane is gone');
  assert.match(invalidPanes.state.error,/panes.*array/i);
  assert.ok(!invalidPanes.commands.some(args=>args[0]==='pane'&&args[1]==='close'));
 }
 const staleRun=await runWorkerCase('run-stale',{runMismatch:true});
 assert.equal(staleRun.state.pending,false);
 assert.equal(staleRun.state.error,'stale close intent refused','stale run cancellation is distinct from command failure');
 assert.deepEqual(staleRun.commands,[],'stale run is rejected before issuing CLI commands');
 const closeFailure=await runWorkerCase('close-failure');
 assert.equal(closeFailure.state.pending,true,'failed close remains retryable');
 assert.ok(closeFailure.commands.some(args=>args[0]==='pane'&&args[1]==='close'),'pane close response is awaited and observed');
 const paneExists=await runWorkerCase('pane-exists');
 assert.equal(paneExists.state.pending,false,'successful pane close clears durable intent');
 assert.ok(paneExists.commands.some(args=>args[0]==='pane'&&args[1]==='close'));
 const emptyPanes=await runWorkerCase('empty-pane-list');
 assert.equal(emptyPanes.state.pending,false,'authoritative empty pane list clears intent');
 assert.ok(!emptyPanes.commands.some(args=>args[0]==='pane'&&args[1]==='close'));
 const staleOwner=await runWorkerCase('owner-stale',{ownerMismatch:true});
 assert.equal(staleOwner.state.pending,false);
 assert.equal(staleOwner.state.error,'registry ownership changed','stale owner cancellation has an explicit reason');
 assert.ok(!staleOwner.commands.some(args=>args[0]==='pane'&&args[1]==='close'));
 const session=join(dir,'child.jsonl');
 Object.assign(process.env,{PI_HERDR_SESSION:session,PI_HERDR_AGENT_ID:'agent',PI_HERDR_RUN_ID:'run',PI_HERDR_SEQUENCE:'1',PI_HERDR_AUTO_EXIT:'1'});
 delete process.env.PI_HERDR_ACTIVITY_FILE;delete process.env.HERDR_PANE_ID;
 writeFileSync(session,'');
 const handlers={},tools=[];let shutdowns=0;
 registerChildExtension({on:(n,h)=>(handlers[n]??=[]).push(h),registerTool:t=>tools.push(t),registerShortcut(){}});
 const emit=async n=>{for(const h of handlers[n]??[])await h({}, {shutdown:()=>shutdowns++});};
 await emit('agent_start');
 const done=tools.find(t=>t.name==='agent_done');
 writeFileSync(session,JSON.stringify({type:'message',message:{role:'assistant',content:[{type:'text',text:'完整结果\nFINAL'}]}})+'\n');
 await done.execute('1',{},undefined,undefined,{shutdown:()=>shutdowns++});
 const eventPath=session+'.completion-run.json';
 const event=readFileSync(eventPath,'utf8');
 await emit('agent_start');
 await done.execute('2',{},undefined,undefined,{shutdown:()=>shutdowns++});
 assert.equal(readFileSync(eventPath,'utf8'),event,'retry never creates another completion event');
 assert.deepEqual(JSON.parse(event).sequence,1);
 const record={name:'child',kind:'pi',agentId:'agent',runId:'run',sequence:1,paneId:'w1:p1',sessionPath:session,stance:'autonomous',submitted:true};
 const recovered=await getAgentResult({target:'run'},{registry:()=>new Map([['child',record]])});
 assert.equal(recovered.data.result,'完整结果\nFINAL','event reference recovers immutable body');
 const bad={...record,delivery:undefined};let closes=0;const pushes=[];
 const deps={registry:()=>new Map([['child',bad]]),fleet:{ok:true,data:[]},load:()=>({notifications:'normal'}),push:p=>pushes.push(p),closePane:async()=>{closes++;return {ok:false,error:{message:'close failed'}}},readSidecar:()=>({state:'ok',sidecar:JSON.parse(event)})};
 await deliverOnce(deps);assert.equal(bad.paneClosePending,true);assert.equal(bad.paneCloseError,'close failed');
 const restored=JSON.parse(JSON.stringify(bad));
 await deliverOnce({...deps,registry:()=>new Map([['child',restored]]),closePane:async()=>{closes++;return {ok:true}}});
 assert.equal(pushes.length,1,'restored retry does not redeliver');assert.equal(restored.paneClosePending,false);
 const stale={...bad,runId:'new-run'};
 await deliverOnce({...deps,registry:()=>new Map([['child',stale]])});assert.equal(closes,2,'stale close cannot close new run');
 const missing={...record,delivery:undefined};const notices=[];
 await deliverOnce({...deps,registry:()=>new Map([['child',missing]]),readSidecar:()=>({state:'ok',sidecar:{type:'done',eventId:'run'}}),push:p=>notices.push(p)});
 assert.equal(missing.delivery,undefined);assert.equal(closes,2);assert.equal(notices[0].details.kind,'persistence-error');
 await deliverOnce({...deps,registry:()=>new Map([['child',missing]]),readSidecar:()=>({state:'ok',sidecar:{type:'done',eventId:'run'}}),push:p=>notices.push(p)});
 assert.equal(notices.length,1,'governance notification is deduplicated');
 console.log('spec43-t2: stable durable event, recovery, close reload/retry and stale guards passed');
}finally{keys.forEach((k,i)=>old[i]===undefined?delete process.env[k]:process.env[k]=old[i]);rmSync(dir,{recursive:true,force:true});}
