import assert from 'node:assert/strict';
import { createJiti } from 'jiti';
import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { execFileSync } from 'node:child_process';
const artifacts = resolve(process.argv[2]);
const run = JSON.parse(readFileSync(join(artifacts, 'run.json')));
for (const k of Object.keys(process.env)) if (/^(HERDR_|PI_HERDR_|PI_SESSION_FILE$)/.test(k)) delete process.env[k];
process.env.HERDR_ENV='1';
process.env.HERDR_WORKSPACE_ID = run.workspace;
const jiti = createJiti(import.meta.url);
const spawn = await jiti.import(join(run.root, 'src/spawn.ts'));
const lifecycle = await jiti.import(join(run.root, 'src/tools/lifecycle.ts'));
const delivery = await jiti.import(join(run.root, 'src/delivery.ts'));
const result = await jiti.import(join(run.root, 'src/tools/result.ts'));
const settings = await jiti.import(join(run.root, 'src/settings.ts'));
const cli = args => { const output = execFileSync('herdr', args, { encoding: 'utf8', timeout: 20000 }); writeFileSync(join(artifacts, 'transport.jsonl'), JSON.stringify({command: ['herdr', ...args], output})+'\n', {flag:'a'}); let r; try { r=JSON.parse(output); } catch { return output; } assert.ok(!r.error, JSON.stringify(r)); return r.result; };
const tab = cli(['tab','create','--workspace',run.workspace,'--cwd',run.scratch,'--label','t5-demo','--no-focus']);
process.env.HERDR_TAB_ID=tab.tab_id;
process.env.HERDR_PANE_ID=tab.root_pane.pane_id;
const owner = join(run.scratch,'parent.jsonl'); writeFileSync(owner,'');
const deps = { parentSession: owner, env: {}, autodrain:false, load:()=>({...settings.DEFAULT_SETTINGS,max_parallel_agents:4, notifications:'none'}), registry:{find:(provider,id)=>({provider,id}),hasConfiguredAuth:()=>true} };
const receipts=[]; const pushes=[];
const tick=async()=>{ await delivery.deliverOnce({push:m=>pushes.push(m),sessionPath:owner,load:deps.load,storePullOnly:true}); if (![...spawn.spawnRecords().values()].some(r=>r.startBeganAt&&!r.submitted&&!r.startError&&!r.delivery)) await spawn.drainQueueOnce(deps); };
const wait=async(predicate)=>{const deadline=Date.now()+45000;while(Date.now()<deadline){await tick();if(await predicate())return;await new Promise(r=>setTimeout(r,250));}throw Error('demo timeout');};
const launch=async(name,prompt,interactive)=>{const r=await spawn.spawnAgent({name,prompt,detach:true,cwd:run.scratch,agent:{name,kind:'pi',interactive,auto_exit:!interactive,agent_args:['-ne','-ns','-e',join(run.root,'tests/fixtures/spec43-t5-child.ts'),'--model','t5-demo/deterministic','--thinking','off']}},deps);assert.ok(r.ok,JSON.stringify(r));return spawn.spawnRecords().get(name);};
const idle=await launch('t5-idle','IDLE PANDA',true);
await wait(()=>existsSync(idle.sessionPath)&&readFileSync(idle.sessionPath,'utf8').includes('T5_FINAL'));
await new Promise(r=>setTimeout(r,1000));
const idleReceipt=await lifecycle.triggerTurn({target:idle.name,text:'IDLE AGAIN'},deps);receipts.push(idleReceipt);assert.ok(idleReceipt.ok);assert.equal(idleReceipt.data.status,'starting');
await wait(()=>readFileSync(idle.sessionPath,'utf8').includes('IDLE AGAIN\\n</herdr-followup> CONTEXT_PANDA=true'));
const busy=await launch('t5-busy','BUSY PANDA',false);
const fleetModule=await jiti.import(join(run.root,'src/herdr.ts'));
await wait(async()=>{ const f=await fleetModule.fleetList();return f.ok&&f.data.some(a=>a.paneId===busy.paneId&&a.agentStatus==='working'); });
const busyReceipt1=await lifecycle.triggerTurn({target:busy.name,text:'FIRST'},deps);const busyReceipt2=await lifecycle.triggerTurn({target:busy.name,text:'SECOND'},deps);receipts.push(busyReceipt1,busyReceipt2);assert.ok(busyReceipt1.ok,JSON.stringify(busyReceipt1));assert.equal(busyReceipt1.data.status,'queued');assert.equal(busyReceipt2.data.status,'queued');
await wait(()=>pushes.some(m=>m.details.runId===busyReceipt2.data.runId));
const original=pushes.find(m=>m.details.name===busy.name && m.details.eventId);assert.ok(original.details.eventId);
const old=await result.getAgentResult({target:original.details.eventId},{registry:()=>spawn.spawnRecords(),hostSession:owner});assert.ok(old.ok,JSON.stringify(old));
const gone=await lifecycle.triggerTurn({target:busy.name,text:'GONE'},deps);receipts.push(gone);assert.ok(gone.ok,JSON.stringify(gone));
await wait(()=>pushes.some(m=>m.details.runId===gone.data.runId));
assert.ok(pushes.find(m=>m.details.runId===gone.data.runId).content.includes('CONTEXT_PANDA=true'));
copyFileSync(idle.sessionPath,join(artifacts,'idle.jsonl'));copyFileSync(busy.sessionPath,join(artifacts,'busy.jsonl'));
writeFileSync(join(artifacts,'terminal.json'),JSON.stringify(cli(['pane','read',idle.paneId,'--source','recent','--lines','100','--format','text'])));
writeFileSync(join(artifacts,'result.json'),JSON.stringify({receipts,pushes,old,realCLI:true,realChildTUI:true,sameSession:busy.sessionPath,agentId:busy.agentId},null,2));
writeFileSync(join(artifacts,'evidence.json'),JSON.stringify({feature:'spec43-t5',boundary:'Real child pi TUI + Herdr CLI + production engines; deterministic model; parent orchestration driven in Node.'}));
run.feature='spec43-t5';run.phase='driven';writeFileSync(join(artifacts,'run.json'),JSON.stringify(run,null,2));
console.log('GREEN idle / busy FIFO / gone same session / old event addressable');
