import assert from 'node:assert/strict';
import {createJiti} from 'jiti';
import {readFileSync,writeFileSync,copyFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {execFileSync} from 'node:child_process';
const artifacts=resolve(process.argv[2]),run=JSON.parse(readFileSync(join(artifacts,'run.json')));
for(const k of Object.keys(process.env)) if(/^(HERDR_|PI_HERDR_|PI_SESSION_FILE$)/.test(k))delete process.env[k];
process.env.HERDR_ENV='1';process.env.HERDR_WORKSPACE_ID=run.workspace;
const jiti=createJiti(import.meta.url),sp=await jiti.import(join(run.root,'src/spawn.ts')),settings=await jiti.import(join(run.root,'src/settings.ts'));
const cli=args=>{const output=execFileSync('herdr',args,{encoding:'utf8',timeout:20000});writeFileSync(join(artifacts,'transport.jsonl'),JSON.stringify({command:['herdr',...args],output})+'\n',{flag:'a'});if(!output.trim())return {};if(!output.trim().startsWith('{'))return output;const r=JSON.parse(output);assert.ok(!r.error,output);return r.result;};
const tab=cli(['tab','create','--workspace',run.workspace,'--cwd',run.scratch,'--label','t9-demo','--no-focus']);process.env.HERDR_TAB_ID=tab.tab_id;process.env.HERDR_PANE_ID=tab.root_pane.pane_id;
const owner=join(run.scratch,'parent.jsonl');writeFileSync(owner,'');
const deps={parentSession:owner,env:{},autodrain:false,load:()=>({...settings.DEFAULT_SETTINGS,max_parallel_agents:5}),registry:{find:(provider,id)=>({provider,id}),hasConfiguredAuth:()=>true}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const wait=async fn=>{for(let i=0;i<180;i++){if(await fn())return;await sleep(250);}throw Error('T9 timeout');};
const launch=async(name,prompt,interactive)=>{const r=await sp.spawnAgent({name,prompt,detach:true,cwd:run.scratch,agent:{name,kind:'pi',interactive,auto_exit:!interactive,agent_args:['-ne','-ns','-e',join(run.root,'tests/fixtures/spec43-t5-child.ts'),'--model','t5-demo/deterministic','--thinking','off']}},deps);assert.ok(r.ok,JSON.stringify(r));const record=sp.spawnRecords().get(name);await wait(()=>existsSync(record.sessionPath)&&readFileSync(record.sessionPath,'utf8').includes('fixture_wait'));return record;};
const direct=await launch('t9-direct','BUSY PANDA',true);
cli(['pane','send-text',direct.paneId,'DIRECT INPUT']);cli(['pane','send-keys',direct.paneId,'Enter']);
await wait(()=>readFileSync(direct.sessionPath,'utf8').includes('T5_FINAL DIRECT INPUT'));
const text=readFileSync(direct.sessionPath,'utf8');assert.ok(text.indexOf('BUSY_TOOL_FINISHED')<text.indexOf('T5_FINAL DIRECT INPUT'),'tool completes before queued input runs');assert.ok(!existsSync(direct.sessionPath+'.takeover'));assert.ok(!existsSync(direct.sessionPath+'.steer'));
const lineage=JSON.stringify(direct.lineage),stance=direct.stance;
cli(['agent','prompt',direct.paneId,'PARENT INPUT']);await wait(()=>readFileSync(direct.sessionPath,'utf8').includes('T5_FINAL PARENT INPUT'));assert.equal(direct.stance,stance);assert.equal(JSON.stringify(direct.lineage),lineage);assert.equal(direct.delivery,undefined);
const draft=await launch('t9-draft','BUSY PANDA',false);cli(['agent','focus',draft.paneId]);cli(['pane','send-text',draft.paneId,'UNSUBMITTED DRAFT']);await wait(()=>existsSync(draft.sessionPath+'.exit'));await wait(()=>!JSON.stringify(cli(['pane','list'])).includes(draft.paneId));assert.ok(!readFileSync(draft.sessionPath,'utf8').includes('UNSUBMITTED DRAFT'));
const interrupted=await launch('t9-interrupt','BUSY PANDA',true);cli(['pane','send-keys',interrupted.paneId,'Escape']);await sleep(1000);assert.ok(!readFileSync(interrupted.sessionPath,'utf8').includes('BUSY_TOOL_FINISHED'));assert.ok(JSON.stringify(cli(['pane','list'])).includes(interrupted.paneId));
const terminal=cli(['pane','read',direct.paneId,'--source','recent','--lines','100','--format','text']);writeFileSync(join(artifacts,'terminal.json'),JSON.stringify(terminal));assert.ok(!JSON.stringify(terminal).includes('user took over'));
for(const [label,r] of [['direct',direct],['draft',draft],['interrupt',interrupted]])copyFileSync(r.sessionPath,join(artifacts,label+'.jsonl'));
writeFileSync(join(artifacts,'result.json'),JSON.stringify({directBusyQueued:true,parentInputInert:true,interactiveResident:true,focusDraftNoProtection:true,explicitInterrupt:true,noMarkers:true,realCLI:true,realChildTUI:true},null,2));
writeFileSync(join(artifacts,'evidence.json'),JSON.stringify({feature:'spec43-t9',boundary:'Real Herdr CLI, child pi TUI, production child extension; deterministic model; Node parent driver.'}));run.feature='spec43-t9';run.phase='driven';writeFileSync(join(artifacts,'run.json'),JSON.stringify(run,null,2));console.log('GREEN direct FIFO / parent inert / draft-focus recycled / explicit interrupt');
