import assert from 'node:assert/strict';
import {createJiti} from 'jiti';
import {mkdtempSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const jiti=createJiti(import.meta.url);
const {registerChildExtension}=await jiti.import('../src/child.ts');
const {deliverOnce}=await jiti.import('../src/delivery.ts');
const {getAgentResult}=await jiti.import('../src/tools/result.ts');
const dir=mkdtempSync(join(tmpdir(),'spec43-t2-'));
const keys=['PI_HERDR_SESSION','PI_HERDR_AGENT_ID','PI_HERDR_RUN_ID','PI_HERDR_SEQUENCE','PI_HERDR_AUTO_EXIT','PI_HERDR_ACTIVITY_FILE','HERDR_PANE_ID'];
const old=keys.map(k=>process.env[k]);
try {
 const session=join(dir,'child.jsonl');
 Object.assign(process.env,{PI_HERDR_SESSION:session,PI_HERDR_AGENT_ID:'agent',PI_HERDR_RUN_ID:'run',PI_HERDR_SEQUENCE:'1',PI_HERDR_AUTO_EXIT:'1'});
 delete process.env.PI_HERDR_ACTIVITY_FILE;delete process.env.HERDR_PANE_ID;
 writeFileSync(session,'');
 const handlers={},tools=[];let shutdowns=0;
 registerChildExtension({on:(n,h)=>(handlers[n]??=[]).push(h),registerTool:t=>tools.push(t),registerShortcut(){}});
 const emit=async n=>{for(const h of handlers[n]??[])await h({}, {shutdown:()=>shutdowns++});};
 await emit('agent_start');
 const done=tools.find(t=>t.name==='agent_done');
 writeFileSync(session,JSON.stringify({type:'message',message:{role:'assistant',content:[{type:'text',text:'完整结果\nFINAL'}]}})+'\n');
 await done.execute('1',{},undefined,undefined,{shutdown:()=>shutdowns++});
 const eventPath=session+'.completion-run.json';
 const event=readFileSync(eventPath,'utf8');
 await emit('agent_start');
 await done.execute('2',{},undefined,undefined,{shutdown:()=>shutdowns++});
 assert.equal(readFileSync(eventPath,'utf8'),event,'retry never creates another completion event');
 assert.deepEqual(JSON.parse(event).sequence,1);
 const record={name:'child',kind:'pi',agentId:'agent',runId:'run',sequence:1,paneId:'w1:p1',sessionPath:session,stance:'autonomous',submitted:true};
 const recovered=await getAgentResult({target:'run'},{registry:()=>new Map([['child',record]])});
 assert.equal(recovered.data.result,'完整结果\nFINAL','event reference recovers immutable body');
 const bad={...record,delivery:undefined};let closes=0;const pushes=[];
 const deps={registry:()=>new Map([['child',bad]]),fleet:{ok:true,data:[]},load:()=>({notifications:'normal'}),push:p=>pushes.push(p),closePane:async()=>{closes++;return {ok:false,error:{message:'close failed'}}},readSidecar:()=>({state:'ok',sidecar:JSON.parse(event)})};
 await deliverOnce(deps);assert.equal(bad.paneClosePending,true);assert.equal(bad.paneCloseError,'close failed');
 const restored=JSON.parse(JSON.stringify(bad));
 await deliverOnce({...deps,registry:()=>new Map([['child',restored]]),closePane:async()=>{closes++;return {ok:true}}});
 assert.equal(pushes.length,1,'restored retry does not redeliver');assert.equal(restored.paneClosePending,false);
 const stale={...bad,runId:'new-run'};
 await deliverOnce({...deps,registry:()=>new Map([['child',stale]])});assert.equal(closes,2,'stale close cannot close new run');
 const missing={...record,delivery:undefined};const notices=[];
 await deliverOnce({...deps,registry:()=>new Map([['child',missing]]),readSidecar:()=>({state:'ok',sidecar:{type:'done',eventId:'run'}}),push:p=>notices.push(p)});
 assert.equal(missing.delivery,undefined);assert.equal(closes,2);assert.equal(notices[0].details.kind,'persistence-error');
 await deliverOnce({...deps,registry:()=>new Map([['child',missing]]),readSidecar:()=>({state:'ok',sidecar:{type:'done',eventId:'run'}}),push:p=>notices.push(p)});
 assert.equal(notices.length,1,'governance notification is deduplicated');
 console.log('spec43-t2: stable durable event, recovery, close reload/retry and stale guards passed');
}finally{keys.forEach((k,i)=>old[i]===undefined?delete process.env[k]:process.env[k]=old[i]);rmSync(dir,{recursive:true,force:true});}
